experiment:
 train_count: 50
  valid_count: 50 
  test_count: 500
  noise_rate: 0.0
  seeds: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  
  device: "cuda:0"
  
model:
  name: "sklogreg"

noise:
  type: "gaussian"
  kwargs:
    mu: 0.0
    sigma: 1.0
    noise_rate: 0.0

output:
  base_dir: "results"
